// Generated by script/generate_status_policy.py; edit policy/session-status.json.
use crate::EventState;
pub(crate) fn codex_event(kind: &str) -> Option<(EventState, bool)> {
    match kind {
        "task_started" => Some((EventState::Working, false)),
        "turn_started" => Some((EventState::Working, false)),
        "task_complete" => Some((EventState::Idle, true)),
        "turn_complete" => Some((EventState::Idle, true)),
        "task_aborted" => Some((EventState::Idle, false)),
        "turn_aborted" => Some((EventState::Idle, false)),
        "request_user_input" => Some((EventState::Waiting, false)),
        "approval_required" => Some((EventState::Waiting, false)),
        _ => None,
    }
}
