// Generated by script/generate_status_policy.py; edit policy/session-status.json.
enum SessionStatusPolicy {
    static let workingSeconds: Double = 120
    static let recentSeconds: Double = 300
    static let codexEvents: [String: (CodexEventState, Bool)] = [
        "task_started": (.working, false),
        "turn_started": (.working, false),
        "task_complete": (.idle, true),
        "turn_complete": (.idle, true),
        "task_aborted": (.idle, false),
        "turn_aborted": (.idle, false),
        "request_user_input": (.waiting, false),
        "approval_required": (.waiting, false),
    ]
    static let claudeAliases: [String: AgentState] = [
        "working": .working,
        "running": .working,
        "busy": .working,
        "processing": .working,
        "waiting": .waiting,
        "waiting_for_input": .waiting,
        "needs_input": .waiting,
        "awaiting_approval": .waiting,
        "waiting_for_permission": .waiting,
        "idle": .idle,
    ]
}
