#!/usr/bin/env python3
"""Generate small adapters from one reviewed status policy; --check is read-only."""
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
policy = json.loads((ROOT / "policy/session-status.json").read_text())
events, aliases = policy["codexEvents"], policy["claudeAliases"]
swift = """// Generated by script/generate_status_policy.py; edit policy/session-status.json.
enum SessionStatusPolicy {
"""
swift += f'    static let workingSeconds: Double = {policy["workingSeconds"]}\n'
swift += f'    static let recentSeconds: Double = {policy["recentSeconds"]}\n'
swift += '    static let codexEvents: [String: (CodexEventState, Bool)] = [\n'
swift += ''.join(f'        "{key}": (.{state}, {str(done).lower()}),\n' for key, (state, done) in events.items())
swift += '    ]\n    static let claudeAliases: [String: AgentState] = [\n'
swift += ''.join(f'        "{key}": .{state},\n' for key, state in aliases.items())
swift += '    ]\n}\n'
rust = """// Generated by script/generate_status_policy.py; edit policy/session-status.json.
use crate::EventState;
pub(crate) fn codex_event(kind: &str) -> Option<(EventState, bool)> {
    match kind {
"""
rust += ''.join(f'        "{key}" => Some((EventState::{state.title()}, {str(done).lower()})),\n' for key, (state, done) in events.items())
rust += '        _ => None,\n    }\n}\n'
labels = {"working": "Working", "idle": "Open · idle", "waiting": "Needs input"}
python = '# BEGIN GENERATED STATUS POLICY\n'
python += 'CODEX_EVENTS = {\n' + ''.join(f'    {key!r}: ({labels[state]!r}, {done!r}),\n' for key, (state, done) in events.items()) + '}\n'
python += 'CLAUDE_ALIASES = {\n' + ''.join(f'    {key!r}: {labels[state]!r},\n' for key, state in aliases.items()) + '}\n'
python += f'WORKING_SECONDS = {policy["workingSeconds"]}\nRECENT_SECONDS = {policy["recentSeconds"]}\n'
python += '# END GENERATED STATUS POLICY'
probe = ROOT / 'Sources/BurroCore/Resources/remote_probe.py'
source = probe.read_text()
if '# BEGIN GENERATED STATUS POLICY' in source:
    start = source.index('# BEGIN GENERATED STATUS POLICY')
    end = source.index('# END GENERATED STATUS POLICY') + len('# END GENERATED STATUS POLICY')
    source = source[:start] + python + source[end:]
else:
    source = source.replace('TAIL_LIMIT = 512 * 1024', 'TAIL_LIMIT = 512 * 1024\n\n' + python)
outputs = {ROOT / 'Sources/BurroCore/SessionStatusPolicy.swift': swift, ROOT / 'Rust/src/status_policy.rs': rust, probe: source}
stale = []
for path, text in outputs.items():
    if '--check' in sys.argv:
        if not path.exists() or path.read_text() != text:
            stale.append(str(path.relative_to(ROOT)))
    else:
        path.write_text(text)
if stale:
    sys.exit('Regenerate status policy: ' + ', '.join(stale))
